### ISSUE TITLE
`make_frame_dataset` fails with NMR structures

### ISSUE THREAD

**Issue by universvm** [wells-wood-research/aposteriori#17]
Using 6CT4 as a structure, `make_frame_dataset` returns the following error:

```
Processing `/Users/leo/Documents/code/dissertation/aposteriori/src/aposteriori/dnn/data/pdb/6ct4.pdb`...
Finished processing files.
There were 1 errors while creating the dataset:
	/Users/leo/Documents/code/dissertation/aposteriori/src/aposteriori/dnn/data/pdb/6ct4.pdb:
		'AmpalContainer' object has no attribute 'get_atoms'
Created frame dataset at `/Users/leo/Documents/code/dissertation/aposteriori/src/aposteriori/dnn/data/frame_dataset_entropy.hdf5` containing 0 residue frames.
```

This, I believe, is due to ampal not returning an ampal structure when handling nmr structure. 'AmpalContainer.get_atoms' should return the atoms of the first structure. 

@ChrisWellsWood what's your opinion on this?

**Comment by ChrisWellsWood** [comment]
Yup, we need to define default behavior with multi-state models. In my opinion, the options are that we either we exclude them or we take one state.

**Comment by universvm** [comment]
I think taking the first state would be the best choice in this case. This is what we also do for the entropy visualization code.
